version: 1

formatters:
    simple:
        format: "%(name)s  |  %(message)s"
    complex:
        format: "%(asctime)s - %(name)s | %(levelname)s | [%(filename)s: %(lineno)d] - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
    
    magnificent_handler:
        class: logging.handlers.RotatingFileHandler
        backupCount: 5
        maxBytes: 10485760 # 10MB
        level: DEBUG
        formatter: complex
        filename : magnificent_health.log

loggers:

    __main__:
        level: DEBUG
        handlers: [console]
        propagate: yes

    magnificent_logger:
        level: DEBUG
        handlers: [console,magnificent_handler]
        propagate: yes
